language : angular_js
angular_js:
  - 1.1.0
  cache : yarn

  install:
    -yarn ci

    script:
      -yarn test
      - yarn run built

      deploy:
        provider: pages
        skip-cleanup : true
        github-token: 
        on:
          branch: gh-pages